[auth]
redirect_uri = "https://appendicitis-complicated-risk-calculator.streamlit.app/oauth2callback"
cookie_secret = "PASTE_RANDOM_COOKIE_SECRET_HERE"
client_id = "PASTE_GOOGLE_CLIENT_ID_HERE"
client_secret = "PASTE_GOOGLE_CLIENT_SECRET_HERE"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

[members]
allowed_emails = [
  "longlk@pnt.edu.vn",
  "dr.lekimlong@gmail.com",
  "dr.thaikhanhphat@gmail.com",
  "trinhan.pham99@gmail.com",
  "quangtran12c1@gmail.com",
  "phucuong98.dn@gmail.com",
  "stellarduong@gmail.com",
  "mytrantrinh42@gmail.com",
  "tg_lenguyenkhoi@pnt.edu.vn"
]

[connections.app_db]
dialect = "postgresql"
driver = "psycopg2"
host = "PASTE_POSTGRES_HOST_HERE"
port = "5432"
database = "PASTE_POSTGRES_DATABASE_HERE"
username = "PASTE_POSTGRES_USERNAME_HERE"
password = "PASTE_POSTGRES_PASSWORD_HERE"
