[auth]
redirect_uri = "https://appendicitis-complicated-risk-calculator.streamlit.app/oauth2callback"
cookie_secret = "W5Vy8UIQq7i4cPFxc24c53jRTzS53Cc6eOAQskP9DUI"
client_id = "806927511658-e4suo065jfnl2ntde3cp63ivc8e53966.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

[members]
allowed_emails = [
  "longlk@pnt.edu.vn",
  "dr.lekimlong@gmail.com",
  "dr.thaikhanhphat@gmail.com",
  "trinhan.pham99@gmail.com",
  "quangtran12c1@gmail.com",
  "phucuong98.dn@gmail.com",
  "stellarduong@gmail.com",
  "mytrantrinh42@gmail.com",
  "tg_lenguyenkhoi@pnt.edu.vn"
]

[connections.app_db]
url = "postgresql://postgres:lPO4d6y8Zi931Iyq@db.eozbkofxwhpwrxqracce.supabase.co:5432/postgres"
